version: "3"

services:
    postgres:
        container_name: db-medilink
        hostname: db-medilink
        image: postgres:latest
        ports:
            - "5432:5432"
        expose:
            - 5432
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - default

    api:
        container_name: medilink-api
        hostname: medilink-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        expose:
            - 3000
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            DB_NAME: postgres
            DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}?schema=public"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - default
        restart: always
        depends_on:
            - postgres

networks:
    default:
        driver: bridge

volumes:
    pg_data:
